name = "views-worker-dev"
type = "webpack"
webpack_config = "webpack.config.js"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[[kv_namespaces]]
binding = "views"
id = ""
preview_id = ""

[vars]
ENV = "development"

[env.production]
name = "views-worker"
[env.production.vars]
ENV = "production"

